accounts/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url
from . import views


app_name = 'account'
urlpatterns = [
	#url(r'^$', views.user_dashboard, name='dashboard'),
	url(r'^$', views.UpdateProfileView.as_view(), name='dashboard'),
	url(r'^delete/?$', views.DeleteAccountView.as_view(), name='delete-account'),
	url(r'^download/?$', views.DownloadView.as_view(), name='download-account'),
#	url(r'^code/?$', views.SetRecoveryCode.as_view(), name='set-recovery-code'),
	url(r'^images/?$', views.ImagesView.as_view(), name='images'),
	url(r'^images/change/?$', views.ChangeImageVisibility.as_view(), name='change-visibility-images'),

	# album shit
	url(r'^images/add/?$', views.AddToAlbum.as_view(), name='add-to-album'),
	url(r'^albums/delete/?$', views.DeleteAlbum.as_view(), name='delete-album'),
	url(r'^albums/remove/?$', views.RemoveImageAlbum.as_view(), name='remove-image-album'),
	url(r'^albums/?$', views.AlbumsView.as_view(), name='albums'),
]

api/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'api'
urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name='api.html'), name='api-home'),
	url(r'^generate/?$', views.CreateKey.as_view(), name='api-create-key'),
	url(r'^delete/?$', views.DeleteKey.as_view(), name='api-delete-key'),
	url(r'^v1.1/upload/?$', views.ApiUpload.as_view(), name='api-upload'),
]

blog/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.blog_home, name='index'),
    url(r'^post/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[^\.]+).html', views.view_post, name='view_post')
]

imglnx/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import TemplateView

from . import views

from django.conf import settings
from django.conf.urls.static import static

import accounts

handler400 = 'imglnx.views.handler400'
handler403 = 'imglnx.views.handler403'
handler404 = 'imglnx.views.handler404'
handler500 = 'imglnx.views.handler500'

urlpatterns = [

	url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
	url(r'^kewlbeans/', admin.site.urls, name='admin'),
	url(r'^blog/', include('blog.urls')),
	url(r'^account/', include('accounts.urls')),

	#url(r'^(?P<filename>[a-zA-Z0-9]+)$', views.ShareView.as_view(), name='share-image'),

	url(r'^api/', include('api.urls'), name='api'),
	url(r'^latest/?$', views.LatestImagesView.as_view(), name='latest-images'),

	# album stuff
	# url(r'^album/new/?$', views.NewAlbumView.as_view(), name='newalbum'),
	url(r'^album/(?P<album_id>[a-zA-Z0-9]+)/?$', accounts.views.ViewAlbumView.as_view(), name='view_album'),

	# auth urls here, because they're just redirects
	url(r'^auth/login/?$', accounts.views.LoginUser.as_view(), name='login'),
	url(r'^auth/register/?$', accounts.views.RegisterUser.as_view(), name='register'),
	#url(r'^auth/forgot/?$', accounts.views.forgot_user.as_view(), name='forgot'),
	#url(r'^auth/forgot/reset/?$', accounts.views.forgot_user_reset.as_view(), name='forgot-reset'),
	url(r'^auth/logout/?$', logout, {'next_page': '/'}, name='logout'),

	# pages
	url(r'^page/faq/?$', TemplateView.as_view(template_name='faq.html'), name='faq'),
	url(r'^page/about/?$', TemplateView.as_view(template_name='about.html'), name='about'),
	url(r'^page/donate/?$', TemplateView.as_view(template_name='donate.html'), name='donate'),
	url(r'^page/contact/?$', views.ContactView.as_view(), name='contact'),
	url(r'^page/contact/thank-you/?$', TemplateView.as_view(template_name='misc/contact-thank-you.html'), name='contact-thanks'),
	url(r'^page/changelog/?$', TemplateView.as_view(template_name='changelog.html'), name='changelog'),
	url(r'^deleted-account/?$', TemplateView.as_view(template_name='misc/deleted-account.html'), name='deleted-account-thanks'),

	# actions
	url(r'^upload/?$', views.uploader, name='image-upload'),
	url(r'^upload/url/?$', views.url_uploader, name='url-image-upload'),

	url(r'^captcha/', include('captcha.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.ARCHIVES_URL, document_root=settings.ARCHIVES_ROOT)
	urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)

imglnx/models.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.core.urlresolvers import reverse
# from django.core.validators import validate_comma_separated_integer_list
from django.conf import settings
import os

class Contact(models.Model):
	email = models.CharField(max_length=128)
	reason = models.CharField(max_length=128) 
	message = models.CharField(max_length=4096)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.reason + ' - ' + str(self.created)

	class Meta:
		verbose_name = 'Contact Request'
		verbose_name_plural = 'Contact Requests'


class Alert(models.Model):
	STYLES = (
		('success', 'Success'),
		('info', 'Info'),
		('warning', 'Warning'),
		('danger', 'Danger')
	)

	title = models.CharField(max_length=256)
	style = models.CharField(max_length=7, choices=STYLES)
	body = models.TextField()
	sticky = models.BooleanField()

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Alert'
		verbose_name_plural = 'Alerts'


class Album(models.Model):
	username = models.CharField(max_length=128)
	album_id = models.CharField(max_length=64)
	title = models.CharField(max_length=32)
	is_private = models.BooleanField(default=False)

	def __str__(self):
		return self.username + ' - ' + self.title

	def get_url(self):
		kwargs = {
			'album_id': self.album_id
		}

		return reverse('view_album', kwargs=kwargs)

	class Meta:
		ordering = ['-id']
		verbose_name = 'Album'
		verbose_name_plural = 'Albums'


class UploadedImage(models.Model):
	album_id = models.CharField(max_length=9)
	username = models.CharField(max_length=128)
	image = models.FileField(default='static/img/image_not_found.png')
	upload_date = models.DateTimeField(auto_now_add=True)
	is_private = models.BooleanField(default=0)
	api_upload_key = models.CharField(max_length=128, default='NULL', blank=True)
	api_upload = models.BooleanField(default=0)

	def __str__(self):
		return self.username + ' - ' + str(self.image) + ' - ' + str(self.upload_date)

	def delete(self, *args, **kwargs):
		img = self.image
		if os.path.isfile(settings.THUMBNAIL_ROOT+'/'+str(img)):
			os.remove(settings.THUMBNAIL_ROOT+'/'+str(img))

		img.delete()
		return super(UploadedImage, self).delete(*args, **kwargs)

	class Meta:
		ordering = ['-id']
		verbose_name = 'Uploaded Image'
		verbose_name_plural = 'Uploaded Images'


@receiver(pre_delete, sender=UploadedImage)
def UploadedImage_delete(sender, instance, **kwargs):
 	instance.image.delete(False)

imglnx/forms.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django import forms
from . models import Contact, Album
from captcha.fields import CaptchaField
from django.utils.translation import ugettext_lazy as _
from django.core.validators import validate_comma_separated_integer_list


class ContactForm(forms.ModelForm):
	captcha = CaptchaField()

	class Meta:
		model = Contact
		fields = [
			'email',
			'reason',
			'message',
			'captcha'
		]


#class NewAlbumForm(forms.ModelForm):

	# class Meta:
	# 	model = Album
	# 	fields = ['title', 'album_image']
	# 	labels = {
	# 		"album_image": _("Album Image"),
	# 		"title": _("Album Title")
	# 	}

imglnx/views.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
import os, random
import urllib.request
import io

from django.shortcuts import (
	render, render_to_response, redirect, 
	HttpResponse, HttpResponseRedirect, reverse,
	get_list_or_404
)
from django.views.generic import View, UpdateView, ListView
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.utils.crypto import get_random_string
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile as TempFile
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from PIL import Image

from .models import UploadedImage, Album
from .forms import ContactForm #, NewAlbumForm

from .utilities import clean_exif, human_readable, do_image_magic



class LatestImagesView(ListView):
	model = UploadedImage
	template_name = 'latest.html'
	context_object_name = 'images'
	queryset = UploadedImage.objects.all().filter(is_private=False).order_by('-id')[:30]


def url_uploader(request):
	errors = ''
	if request.method == 'POST' and request.POST['image']:
		try:
			requested_url = urllib.request.urlopen(request.POST['image'])
		except:
			return JsonResponse({'errors': 'Site returned a 403, 404, or is down!'})

		if requested_url.getcode() == 200:
			# do head request here to get 
			mimetype = requested_url.headers['content-type']
			image_size = int(requested_url.headers['content-length'])
			fname = os.path.basename(request.POST['image']) 
			extension = os.path.splitext(fname)[1]

			if mimetype in settings.IMAGE_TYPES and extension.lower() in settings.EXT:
				if image_size <= settings.IMAGE_MAX_SIZE:

					# check file extensions
					# if any(settings.EXT in fname for settings.EXT in settings.EXT):
					# 	print('yes')
					# else:
					# 	print('no')

					# this is hacky, but it'll do for now
					if '?' in fname or ':' in fname:
						extension = '.jpg'
					# 	extension = os.path.splitext(fname.split('?')[0])[1]
					#else:
					#	extension = os.path.splitext(fname)[1]

					
					fs = FileSystemStorage()
					upload_hash = get_random_string(length=settings.HASH_LENGTH)

					# simple fix to avoid collisions
					if os.path.isfile(upload_hash + extension.lower()):
						upload_hash = get_random_string(length=settings.HASH_LENGTH+1)

					filename = fs.save(upload_hash + extension.lower(), io.BytesIO(requested_url.read()))
					#path = fs.url(filename)   # returns /i/hash.ext

					try:
						if Image.open(settings.MEDIA_ROOT+'/'+filename):
							pass
					except Exception as e:
						os.remove(settings.MEDIA_ROOT+'/'+filename) # delete the corrupt/invalid image
						return JsonResponse({"image": "", "status": 403, "error": "Not a valid image! Aka the image is incomplete, altered in someway, or it's just not an image."})

					do_image_magic(request, filename)

					return JsonResponse({"image": settings.MEDIA_URL+filename, "status": 200, "error": False})
				else:
					errors = 'Image is too large!'	
			else:
				errors = 'Image type not allowed!' 

	return render(request, 'home.html', {'errors': errors})


def uploader(request):
	errors = ''
	if request.method == 'POST' and request.FILES['images']:

		uploaded_image = request.FILES['images']
		fs = FileSystemStorage()
		name, extension = os.path.splitext(uploaded_image.name)
		upload_hash = get_random_string(length=settings.HASH_LENGTH) 

		# simple fix to avoid collisions
		if os.path.isfile(upload_hash + extension.lower()): 
			upload_hash = get_random_string(length=settings.HASH_LENGTH+1)
		
		if uploaded_image.content_type in settings.IMAGE_TYPES and extension.lower() in settings.EXT:
			if uploaded_image.size <= settings.IMAGE_MAX_SIZE:
				filename = fs.save(upload_hash + extension.lower(), uploaded_image)

				# to write webm we have to write by chunks like tmpfile fs.save doesn't work for webm for some reason

				try:
					if Image.open(settings.MEDIA_ROOT+'/'+filename):
						pass
				except Exception as e:
					os.remove(settings.MEDIA_ROOT+'/'+filename) # delete the corrupt/invalid image
					return JsonResponse({"image": "", "status": 403, "error": "Not a valid image! Aka the image is incomplete, altered in someway, or it's just not an image."})

				do_image_magic(request, filename)

				return JsonResponse({"image": settings.MEDIA_URL+filename, "status": 200, "error": False})
			else:
				errors = 'File size is too large! Your size was ' + str(human_readable(uploaded_image.size)) + \
				' we only allow ' + str(human_readable(settings.IMAGE_MAX_SIZE)) + '.'
		else:
			errors = 'File type isn\'t allowed!'

	return JsonResponse({"image": "", "status": 403, "error": errors})


class ContactView(View):
	form_class = ContactForm
	template_name = 'contact.html'

	def get(self, request):
		form = self.form_class(None)

		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = ContactForm(request.POST)

		if form.is_valid():
			email = form.cleaned_data['email']
			reason = form.cleaned_data['reason']
			message = form.cleaned_data['message']
			form.save()

			return redirect('contact-thanks')

		return render(request, self.template_name, {'form': form, 'errors': form.errors})


class NewAlbumView(View):
#	form_class = NewAlbumForm
	template_name = 'imglnx/album_form.html'

	def get(self, request):
		form = self.form_class(None)
		images = UploadedImage.objects.filter(username=request.user.get_username())

		return render(request, self.template_name, {'form': form, 'images': images})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			album = form.save(commit=False)
			album.album_title = form.cleaned_data['title']
			album.username = request.user
			for selected in request.POST.getlist('addtoalbum'):
				album.stored_images += selected + ','
			album.save()

		return redirect('home')


"""
Error pages
"""
def handler400(request):
	return render(request, 'error_pages/400.html', status=400)

def handler403(request):
	return render(request, 'error_pages/403.html', status=403)

def handler404(request):
	return render(request, 'error_pages/404.html', status=404)

def handler500(request):
	return render(request, 'error_pages/500.html', status=500)

imglnx/templates/_base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="imglnx.com is an image hosting service that allows users to upload images. - free, fast, secure, simple, image hosting">
		<meta name="keywords" content="imglnx, imglnx.com, imglnx com, image, images, video, videos, image hosting, img hosting, img, imgs, share, upload, uploading, uploader">
		{% load static %}
		<!-- Add the favicon to the page -->
		<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

		<title>{% block title %}BASE{% endblock %}</title>

		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}" />
		<link rel="stylesheet" href="{% static 'css/noty.css' %}" />

		<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<script src="{% static 'js/noty.min.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		{% block head %}{% endblock %}
	</head>
	<body>
	{% load base_tags %}
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" /></a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					{% block nav-home %}<li><a href="{% url 'home' %}">Home</a></li>{% endblock %}
					{% block nav-about %}<li><a href="{% url 'about' %}">About</a></li>{% endblock %}
					{% block nav-blog %}<li><a href="{% url 'blog:index' %}">Blog</a></li>{% endblock %}
					{% block nav-faq %}<li><a href="{% url 'faq' %}">FAQ</a></li>{% endblock %}
					{% block nav-contact %}<li><a href="{% url 'contact' %}">Contact</a></li>{% endblock %}
					{% block nav-api %}<li><a href="{% url 'api:api-home' %}">API</a></li>{% endblock %}
					
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, {{ user.username }} <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'account:dashboard' %}"><i class="fa fa-cog pull-right" aria-hidden="true"></i>Dashboard</a></li>
							<li><a href="{% url 'account:images' %}"><i class="fa fa-image pull-right" aria-hidden="true"></i>Images ({{ user.username|get_user_images_count }})</a></li>
							<li><a href="{% url 'account:albums' %}"><i class="fa fa-book pull-right" aria-hidden="true"></i>Albums ({{ user.username|get_user_albums_count }})</a></li>
							<li class="divider"></li>
							<li><a href="#" id="logout"><i class="fa fa-sign-out pull-right" aria-hidden="true"></i> Logout</a></li>
						</ul>
					</li>
					{% else %}
					<li><a href="{% url 'login' %}">Login</a></li>
					<li><a href="{% url 'register' %}">Register</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
	<noscript><div class="alert alert-danger" role="alert">Yikes! Imglnx uses JavaScript and you do not. Please enable JavaScript so your time here will be better and more stable.<br />For full functionality of this site it is necessary to enable JavaScript. Here are the <a class="alert-link" href="http://www.enable-javascript.com/" target="_blank" rel="noopener noreferrer"> instructions how to enable JavaScript in your web browser</a>.</div></noscript>

	{% for alert in alerts %}
	<div class="alert alert-{{ alert.style }} alert-dismissible" role="alert">
		{% if not alert.sticky %} <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> {% endif %}
		<strong>{{ alert.title }}</strong>&emsp;{{ alert.body|safe }}
	</div>
	{% endfor %}

	{% block content %}
		<div class="jumbotron">
			<h1>Navbar example</h1>
			<p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
			<p>To see the difference between static and fixed top navbars, just scroll.</p>
			<p>
				<a class="btn btn-lg btn-primary" href="#" role="button">View navbar docs &raquo;</a>
			</p>
		</div>
	{% endblock %}
	</div>

	<footer class="footer">
		<p class="text-muted">
			<span class="logos">
				<!-- <a class="tmpfile" href="https://tmpfile.org" title="tmpfile.org is a sister service that allows you to upload files for 24 hours and text files for 2 hours."></a> -->
			</span>
			<span class="pull-left">
			imglnx v<a href="{% url 'changelog' %}">{{ VERSION }}</a>
			</span>	
			<span class="pull-right">
				We're hosting <a href="{% url 'latest-images' %}" title="View the latest uploaded images">{{ ''|get_hosted_count }}</a> images totaling at {{ ''|get_hosted_size }}.
			</span>	
		</p>
	</footer>


	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/sweetalert.min.js' %}"></script>
	{% block js_end %}{% endblock %}
	</body>
</html>

imglnx/templates/about.html
{% extends '_base.html' %}

{% block title %}About{% endblock %}

{% block nav-about %}
<li class="active"><a href="#">About</a></li>
{% endblock %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-heading"><h5>About</h5></div>
	<div class="panel-body">
		<!-- History/About -->
		<h2>About imglnx</h2>
		<p>imglnx is a free image hosting service originally created in August 2013 then quickly disbanded has reformed in December 2016.<br />
			imglnx is working to become a widely used image host that doesn't <strong>log identifiable information</strong>, <strong>track you</strong>, or <strong>have ads</strong>.<br />
			The more imglnx grows the more we'll continue to update the site with new features and more servers.<br /><br />
			Remember, we're not designers we're programmers. :)
		</p>

		<br />
		<!-- Legal -->
		<h2>Legal Information</h2>
		<p>A <a href="/static/downloads/canary.txt">warrant canary</a> is available.</p>
		<p>imglnx/imglnx.com staff reserves the right to delete any image (if breaking a rule or country law where we're hosted) and or ban an abusive ip address*/user at any time without any notice. imglnx/imglnx.com staff also reserve the right to modify these terms at any time with a 15 day notice displayed on all pages before the changes go live.<br />
		imglnx/imglnx.com service is a provided as-is with no implied warranties of any kind. We can not be held responsible for the loss of data or other damages which
		may result from (lack of) functionality of our service.<br /><br />
		With that being said, we do not take any responsibility for the images hosted on any of our servers.<br />
		If you believe an image is breaking any of our rules or laws in the country that we're hosted in please report them.<br /><br />
		Any and all content is allowed with the exception of a few things listed below. (just to keep us out of prison ;))<br />
		<ul>
			<li>Anything illegal under Romanian law</li>
			<li>Child Pornography/Nudity/Modeling</li>
			<li>Content that promotes terrorism</li>
		</ul>
		<br />
		* You said you don't log any data!?!!! Correct, we don't - however, if we notice that the service is being abused we'll enable logging of connections for a short time so we can ban the ip address from the service. (We use <code>access_log off;</code> in our nginx config and write logs to /dev/null every 10 minutes incase our config writes logs.)

		<br />
		<!-- Privacy Policy -->
		<h2>Data we store/collect</h2>
		<ol>
			<li>Username - <em>used for logging you in</em></li>
			<li>Password - <em>well to login?</em></li>
			<li>Register Date - <em>help determine if an account has been inactive</em></li>
			<li>Last Activity Date - <em>help determine if an account has been inactive</em></li>
			<li>Media (images) - <em>well... you uploaded them so?</em></li>
			<li>Media Upload Date - <em>so we can delete them after X time in the future</em></li>
		</ol>
		If we have a security issue that affects our users data, we'll notify you via email, our <a href="https://twitter.com/imglnx">Twitter</a>, and any other resources we're able to post on. We take the security and privacy of our users very seriously and will notify you immediately if an issue arises. 
	</div>
	<div class="panel-footer"></div>
</div>
{% endblock %}

imglnx/templates/contact.html
{% extends '_base.html' %}

{% block title %}Contact{% endblock %}

{% block nav-contact %}
<li class="active"><a href="#">Contact</a></li>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6 col-md-offset-3">
    {% for error in errors %}
    {{ error }}
    {% endfor %}
		<form method="POST" class="form-horizontal">
			<div class="panel panel-default">
				<div class="panel-heading"><h5>Contact</h5></div>
				<div class="panel-body">
					<p>Alternatively instead of using this form you can tweet us <a href="https://twitter.com/imglnx" target="_blank" rel="noopener noreferrer">@imglnx</a> or even email us at <a href="mailto:contact@imglnx.com">contact@imglnx.com</a> (<a href="/static/downloads/contact.asc">GPG</a>). <strong>NOTE: Our email isn't hosted by us so please use GPG when mailing us!</strong></p><br />
					{% csrf_token %}
					<div class="form-group">
						<label for="email" class="col-sm-2 control-label">Email*</label>
						<div class="col-sm-10">
							<input type="email" class="form-control" id="email" name="email" placeholder="Email" {% if user.is_authenticated %}value="{{ request.user.email }}"{% endif %} required>
							<p class="help-block">So we can contact you if it's necessary.</p>
						</div>
					</div>
					<div class="form-group"> 
						<label for="reason" class="col-sm-2 control-label">Reason for Contact*</label>
						<div class="col-sm-10">
							<select class="form-control" id="reason" name="reason" required>
								<option>Image Removal / Private Information Exposed</option>
								<option>Image Removal / Against ToS</option>
								<option>Image Removal / Other</option>
								<option>Feature Request</option>
								<option>Feedback</option>
								<option>Other</option>
							</select>
							<p class="help-block">Why are you contacting us?</p>
						</div>
					</div>
					<div class="form-group"> 
						<label for="message" class="col-sm-2 control-label">Message*</label>
						<div class="col-sm-10">
							<textarea class="form-control" id="message" name="message" rows="3" required></textarea>
							<p class="help-block">Provide some information regarding why you're contacting us.</p>
						</div>
					</div>
					<div class="form-group"> 
						<label for="message" class="col-sm-2 control-label">{{ form.captcha.label_tag }}</label>
						<div class="col-sm-10">
							{{ form.captcha }}
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<span class="pull-right"><button class="btn btn-success" type="submit">Submit</button></span>
					<div class="clearfix"></div>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

imglnx/templates/latest.html
{% extends '_base.html' %}
{% load static %}
{% load base_tags %}

{% block title %}Latest Images{% endblock %}

{% block content %}
<h2>Latest Images</h2>
<div class="row">
	{% for image in images %}
	<div class="col-xs-6 col-md-2">
		<div class="image-wrapper">
			<a href="{{ MEDIA_URL }}{{ image.image }}"><img class="center-block" src="{{ image.image|get_thumbnail }}" /></a>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}