api/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'api'
urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name='api.html'), name='api-home'),
	url(r'^generate/?$', views.CreateKey.as_view(), name='api-create-key'),
	url(r'^delete/?$', views.DeleteKey.as_view(), name='api-delete-key'),
	url(r'^v1.1/upload/?$', views.ApiUpload.as_view(), name='api-upload'),
]

imglnx/urls.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import TemplateView

from . import views

from django.conf import settings
from django.conf.urls.static import static

import accounts

handler400 = 'imglnx.views.handler400'
handler403 = 'imglnx.views.handler403'
handler404 = 'imglnx.views.handler404'
handler500 = 'imglnx.views.handler500'

urlpatterns = [

	url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
	url(r'^kewlbeans/', admin.site.urls, name='admin'),
	url(r'^blog/', include('blog.urls')),
	url(r'^account/', include('accounts.urls')),

	#url(r'^(?P<filename>[a-zA-Z0-9]+)$', views.ShareView.as_view(), name='share-image'),

	url(r'^api/', include('api.urls'), name='api'),
	url(r'^latest/?$', views.LatestImagesView.as_view(), name='latest-images'),

	# album stuff
	# url(r'^album/new/?$', views.NewAlbumView.as_view(), name='newalbum'),
	url(r'^album/(?P<album_id>[a-zA-Z0-9]+)/?$', accounts.views.ViewAlbumView.as_view(), name='view_album'),

	# auth urls here, because they're just redirects
	url(r'^auth/login/?$', accounts.views.LoginUser.as_view(), name='login'),
	url(r'^auth/register/?$', accounts.views.RegisterUser.as_view(), name='register'),
	#url(r'^auth/forgot/?$', accounts.views.forgot_user.as_view(), name='forgot'),
	#url(r'^auth/forgot/reset/?$', accounts.views.forgot_user_reset.as_view(), name='forgot-reset'),
	url(r'^auth/logout/?$', logout, {'next_page': '/'}, name='logout'),

	# pages
	url(r'^page/faq/?$', TemplateView.as_view(template_name='faq.html'), name='faq'),
	url(r'^page/about/?$', TemplateView.as_view(template_name='about.html'), name='about'),
	url(r'^page/donate/?$', TemplateView.as_view(template_name='donate.html'), name='donate'),
	url(r'^page/contact/?$', views.ContactView.as_view(), name='contact'),
	url(r'^page/contact/thank-you/?$', TemplateView.as_view(template_name='misc/contact-thank-you.html'), name='contact-thanks'),
	url(r'^page/changelog/?$', TemplateView.as_view(template_name='changelog.html'), name='changelog'),
	url(r'^deleted-account/?$', TemplateView.as_view(template_name='misc/deleted-account.html'), name='deleted-account-thanks'),

	# actions
	url(r'^upload/?$', views.uploader, name='image-upload'),
	url(r'^upload/url/?$', views.url_uploader, name='url-image-upload'),

	url(r'^captcha/', include('captcha.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.ARCHIVES_URL, document_root=settings.ARCHIVES_ROOT)
	urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)

api/models.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.db import models

# Create your models here.
class APIKeys(models.Model):
	username = models.CharField(max_length=256)
	description = models.CharField(max_length=512)
	api_key = models.CharField(max_length=128)
	upload_count = models.IntegerField()
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.username + ' - ' + str(self.created)

	class Meta:
		app_label = 'imglnx'
		verbose_name = 'API Key'
		verbose_name_plural = 'API Keys'

api/views.py
"""
BSD 3-Clause License

Copyright (c) 2016-2019 Russ 'trdwll' Treadwell. All rights reserved.
"""
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic.edit import View
from django.conf import settings
from django.utils.crypto import get_random_string
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from PIL import Image

import os, subprocess

from imglnx.models import UploadedImage
from api.models import APIKeys

from imglnx.utilities import clean_exif, is_logged_in, human_readable


class DeleteKey(View):

	def get(self, request):
		if not is_logged_in(request):
			return redirect('login')
		
		return redirect('account:dashboard')

	def post(self, request):
		if not is_logged_in(request):
			return redirect('login')

		APIKeys.objects.filter(username=request.user.get_username(), api_key=request.POST.get('api_key', '')).delete()
		return redirect('account:dashboard')


class CreateKey(View):
	template_name = 'generate.html'

	def get(self, request):
		if not is_logged_in(request):
			return redirect('login')

		return redirect('account:dashboard')

	def post(self, request):
		if not is_logged_in(request):
			return redirect('login')

		
		# only allow 5 API keys to be generated
		# TODO: add error messages on the render of the template
		cnt = APIKeys.objects.filter(username=request.user.get_username()).count()

		if cnt < 5:
			k = APIKeys(username=request.user.get_username(), api_key=get_random_string(length=32), upload_count=0)
			k.save()

		return redirect('account:dashboard')


@method_decorator(csrf_exempt, name='dispatch')
class ApiUpload(View):
	template_name = ''

	def get(self, request):
		return JsonResponse({"error": "You are not allowed to do GET requests here!"})

	def post(self, request):
		error = ''
		if request.FILES['images']:
			uploaded_image = request.FILES['images']
			fs = FileSystemStorage()
			name, extension = os.path.splitext(uploaded_image.name)
			upload_hash = get_random_string(length=settings.HASH_LENGTH) 

			# simple fix to avoid collisions
			if os.path.isfile(upload_hash + extension.lower()):
				upload_hash = get_random_string(length=settings.HASH_LENGTH+1)
			
			if uploaded_image.content_type in settings.IMAGE_TYPES and extension.lower() in settings.EXT:
				if uploaded_image.size <= settings.IMAGE_MAX_SIZE:
					filename = fs.save(upload_hash + extension.lower(), uploaded_image)
					#path = fs.url(filename) # returns /i/hash.ext

					try:
						# if user has api keys and if that key in the POST is on their account
						user_key = APIKeys.objects.filter(api_key=request.POST.get('auth_token', '')).values_list('username', flat=True).get()
						user_keycount = APIKeys.objects.filter(username=user_key).count()

						# check if the API key is valid then set the uploader username to the apikey owner
						if user_key and user_keycount >= 1: # the >= 1 is unnecessary since user_key is checking if the key is valid, but #yolo
							username = user_key # kinda bad naming, but returns the username of the auth_token/api_key owner ;)
						else:
							username = 'Anonymous Upload'
					except:
						username = 'Anonymous Upload'

					# check if request.user is a real user and check if that user is permitted to use the api key
					# if the request.user isn't a user then upload anonymously (without a key) and if the user exists, 
					# but the key doesn't for that user upload anonymously

					new_count = UploadedImage.objects.filter(api_upload_key=request.POST.get('auth_token', '')).count() + 1
					APIKeys.objects.filter(api_key=request.POST.get('auth_token', '')).update(upload_count=new_count)

					image = UploadedImage()
					image.username = username
					image.image = filename
					
					if username is not 'Anonymous Upload' and request.POST.get('private'):
						image.is_private = True
					else:
						image.is_private = False

					image.api_upload_key = request.POST.get('auth_token', '')
					image.api_upload = True
					image.save()

					clean_exif(settings.MEDIA_ROOT+'/'+filename)

					try:
						subprocess.call(["convert", "-thumbnail", "150x150", settings.MEDIA_ROOT+'/'+filename, settings.THUMBNAIL_ROOT+'/'+filename])
					except Exception as e:
						raise e

					return JsonResponse({"image": settings.MEDIA_URL+filename, "status": 200})
				else:
					error = 'File size is too large! Your size was ' + str(human_readable(uploaded_image.size)) + \
				' we only allow ' + str(human_readable(settings.IMAGE_MAX_SIZE)) + '.'
			else:
				error = 'Image type not allowed!'
		else:
			error = 'No image set to upload!'

		return JsonResponse({'error': error, "status": 403})

api/templates/api.html
{% extends '_base.html' %}
{% load static %}

{% block title %}API{% endblock %}

{% block nav-api %}
<li class="active"><a href="#">API</a></li>
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-info">
{{ errors|safe }}
</div>
{% endif %}
<div class="panel panel-default">
<div class="panel-heading"><h5>API Documentation</h5></div>
	<div class="panel-body">
		Send a <code>POST</code> request to <code>https://(www.)imglnx.com/api/v1.1/upload/</code>. The available args are listed below.<br /><br />
		<ul>
			<li><code>auth_token</code> = Your unique API key - if NULL or doesn't exist then the image will be uploaded as Anonymous Upload</li>
      <li><code>private</code> = Makes all of your API uploads private from the <a href="{% url 'latest-images' %}">latest</a> page. (will eventually be a proper private upload)</li>
		</ul>
		For people that don't know how to set this up manually, import this into your ShareX app. Make sure you replace <code>MY_AUTH_TOKEN_HERE</code> with your auth_token, else the image will be upload anonymously.<br />
<pre class="pre-style">
{
  "Name": "imglnx",
  "DestinationType": "ImageUploader",
  "RequestType": "POST",
  "RequestURL": "https://imglnx.com/api/v1.1/upload/",
  "FileFormName": "images",
  "Arguments": {
    "auth_token": "MY_AUTH_TOKEN_HERE",
    "private": "False"
  },
  "ResponseType": "Text",
  "URL": "$json:image$"
}
</pre>
	</div>
	<div class="panel-footer"></div>
</div>

{% endblock %}

api/templates/generate.html
<table class="table" id="api-keys-table">
	{% if api_keys|length >= 1 %}
		<tr><th>API Key</th><th>Created on</th><th>Images Uploaded</th><th></th></tr>
		{% for api in api_keys %}
		<tr><td>{{ api.api_key }}</td>
		<td>{{ api.created }}</td>
		<td>{{ api.upload_count }}</td>
		<td><button name="{{ api.api_key }}" class="btn btn-danger btn-xs delete-api-key"><i class="fa fa-times" aria-hidden="true"></i></button></td></tr>
		{% endfor %}
	{% else %}
	<div class="alert alert-danger">Oh no! You don't have any API Keys! Generate one now!!!</div>
	{% endif %}
</table>

<form method="POST" class="form-horizontal" enctype="multipart/form-data" action="{% url 'api:api-create-key' %}"> 
    {% csrf_token %}
	<button class="btn btn-success" type="submit" {% if api_keys|length >= 5 %}disabled{% endif %}>Generate New Token</button>
	<div class="clearfix"></div>
</form>